/**
 * A promotion right earned by a move may be spent on that same move
 * (rules.txt, the `a4=B` example). `applyMove` implements this and the UI
 * offers it, but the two candidate generators used by the search once read the
 * rights *before* the move's own counter tick — so the AI was blind to every
 * earn-and-spend evolution, its own and the opponent's.
 *
 * Regression case: data/games/game1.txt, where 7. Bb8=R# (White's third minor
 * move, earning and spending the rook right at once) was mate and the engine
 * scored the position at -0.89 at depth 5.
 */
import { describe, it, expect } from "vitest";
import { EvoChessGame } from "../game";
import type { Square } from "chess.js";
import { legalTurns, chooseMove } from "../ai";
import { fromEvoGame, generateEvoTurns, turnKey } from "../evoBitboard";

function push(game: EvoChessGame, uci: string, options = {}) {
  return game.applyMove(uci.slice(0, 2) as Square, uci.slice(2, 4) as Square, options);
}

/** Position after 6...g4 in data/games/game1.txt: White mates with Bb8=R. */
function mateInOnePosition(): EvoChessGame {
  const game = new EvoChessGame();
  push(game, "e2e4");
  push(game, "g7g5");
  push(game, "d2d4");
  push(game, "b7b6");
  push(game, "g2g3", { minorPromo: "b" });
  push(game, "c7c6");
  push(game, "g3b8");
  push(game, "a7a6");
  push(game, "b8c7");
  push(game, "a6a5", { minorPromo: "b" });
  push(game, "c2c3");
  push(game, "g5g4");
  return game;
}

describe("a right earned by a move can be spent on that same move", () => {
  it("is legal in the reference engine (Bb8=R#)", () => {
    const game = mateInOnePosition();
    expect(game.rookRights.w).toBe(0); // not yet earned before the move
    expect(game.minorMoveProgress.w).toBe(2);
    expect(push(game, "c7b8", { rookPromo: true })).toBe("Bb8=R#");
    expect(game.chess.isCheckmate()).toBe(true);
  });

  it("is generated by candidateTurns (ai.ts)", () => {
    const game = mateInOnePosition();
    const keys = legalTurns(game).map((c) => `${c.from}${c.to}${c.options.rookPromo ? "=R" : ""}`);
    expect(keys).toContain("c7b8=R");
  });

  it("is generated by generateEvoTurns (bitboard)", () => {
    const game = mateInOnePosition();
    const keys = generateEvoTurns(fromEvoGame(game)).map(turnKey);
    expect(keys).toContain("c7b8|R");
  });

  it("the search finds the mate", () => {
    const game = mateInOnePosition();
    const best = chooseMove(game, 3, 1);
    expect(best).not.toBeNull();
    expect(`${best!.from}${best!.to}`).toBe("c7b8");
    expect(best!.options.rookPromo).toBe(true);
  });

  it("a minor right earned by the third pawn move is spendable on it", () => {
    const game = new EvoChessGame();
    push(game, "a2a3");
    push(game, "h7h6");
    push(game, "b2b3");
    push(game, "h6h5");
    expect(game.minorRights.w).toBe(0);
    expect(game.pawnMoveProgress.w).toBe(2);
    const keys = generateEvoTurns(fromEvoGame(game)).map(turnKey);
    expect(keys).toContain("c2c3|b");
    const aiKeys = legalTurns(game).map(
      (c) => `${c.from}${c.to}${c.options.minorPromo ?? ""}`
    );
    expect(aiKeys).toContain("c2c3b");
  });
});
