/**
 * The TypeScript half of the golden-vector parity gate (milestone 3) — the
 * genuine cross-language check.
 *
 * `training/parity/golden.json` was generated by the Python extractor. This
 * test runs the *same* fixtures through the TypeScript extractor and asserts
 * byte-identical active indices. If it fails, the two extractors have drifted,
 * and a net trained on the Python features would be fed different inputs at
 * play time — the silent-failure mode the whole milestone exists to prevent.
 *
 * The fixtures are stored in Python's `Position.to_json` shape (zero-valued
 * fields omitted), so `positionFromFixture` mirrors `Position.from_json`.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import type { Color } from "chess.js";
import {
  activeIndices,
  extract,
  FEATURE_SIZE,
  type NnuePosition,
} from "../nnueFeatures";

const here = dirname(fileURLToPath(import.meta.url));
const parityDir = resolve(here, "../../../training/parity");

interface FixtureJson {
  fen: string;
  minorRights?: [number, number];
  rookRights?: [number, number];
  pawnMoveProgress?: [number, number];
  minorMoveProgress?: [number, number];
  rookCharges?: Record<string, number>;
  rookLocked?: string[];
  epEvolved?: [string, string, Color];
}

function pair(value: [number, number] | undefined): Record<Color, number> {
  const [w, b] = value ?? [0, 0];
  return { w, b };
}

/** Mirror of Position.from_json in position.py, into an NnuePosition. */
function positionFromFixture(json: FixtureJson): NnuePosition {
  return {
    fen: json.fen,
    minorRights: pair(json.minorRights),
    rookRights: pair(json.rookRights),
    pawnMoveProgress: pair(json.pawnMoveProgress),
    minorMoveProgress: pair(json.minorMoveProgress),
    rookCharges: new Map(Object.entries(json.rookCharges ?? {})),
    rookLocked: new Set(json.rookLocked ?? []),
    epEvolved: json.epEvolved
      ? { skipped: json.epEvolved[0], victim: json.epEvolved[1], color: json.epEvolved[2] }
      : null,
  };
}

const fixtures: { name: string; position: FixtureJson }[] = JSON.parse(
  readFileSync(resolve(parityDir, "fixtures.json"), "utf8")
);
const golden: { name: string; active: number[] }[] = JSON.parse(
  readFileSync(resolve(parityDir, "golden.json"), "utf8")
);
const goldenByName = new Map(golden.map((r) => [r.name, r.active]));

describe("NNUE feature parity with Python", () => {
  it("has a fixture for every golden record and vice versa", () => {
    expect(fixtures.map((f) => f.name).sort()).toEqual(golden.map((g) => g.name).sort());
  });

  it.each(fixtures)("$name matches the Python golden vector", ({ name, position }) => {
    const expected = goldenByName.get(name);
    expect(expected, `no golden vector named ${name}`).toBeDefined();
    expect(activeIndices(positionFromFixture(position))).toEqual(expected);
  });
});

describe("NNUE feature extractor internals", () => {
  const start: NnuePosition = positionFromFixture({ fen: "4k3/pppppppp/8/8/8/8/PPPPPPPP/4K3 w - - 0 1" });

  it("produces a binary vector of the declared size", () => {
    const vector = extract(start);
    expect(vector.length).toBe(FEATURE_SIZE);
    expect(vector.every((v) => v === 0 || v === 1)).toBe(true);
  });

  it("marks 18 pieces active in the start position", () => {
    // 16 pawns + 2 kings, plus the eight dense zero-bucket one-hots.
    expect(activeIndices(start).length).toBe(18 + 8);
  });

  it("encodes the start position identically from either side (mirroring)", () => {
    const black = positionFromFixture({ fen: "4k3/pppppppp/8/8/8/8/PPPPPPPP/4K3 b - - 0 1" });
    expect(activeIndices(black)).toEqual(activeIndices(start));
  });
});
